function loadvocab() {
vocab = [
	["le projet de loi","der Gesetzentwurf"],
	["exception","ausnahme"],
	["approbation","genehmigung"],
	["le code du travail","das französisches Arbeitsgesetzbuch"],
	["un accord","die Vereinbarung"],
	["entreprise","Betrieb"],
	["la convention collective","der Tarifvertrag"],
	["la primauté","der Vorrang"],
	["travail saisonnier","saisonale Beschäftigung"],
	["le temps de travail","die Arbeitszeit"],
	["la durée de travail maximale","die Höchstarbeitszeit"],
	["fixer","festsetzen"],
	["le poste","die Schicht"],
	["le travail de nuit","der Nachtdienst"],
	["les heures supplémentaires","die Überstunden"],
	["le décompte","die Abrechnung"],
	["le plancher","die Untergrenze"],
	["le plafond","die Obergrenze"],
	["la dérogation","die Ausnahmegenehmigung"],
	["autorité administrative","Behörde"],
	["le délégué du personnel","der Personalvertreter"],
	["le syndicat","die Gewerkschaft"],
	["difficultés économiques","wirtschaftliche Schwierigkeiten"],
	["suppressions d’emploi","Stellenstreichungen"],
	["supprimer des emplois","Stellen streichen"],
	["la compétitivité","die Wettbewerbsfähigkeit"],
	["le contrat de travail","der Arbeitsvertrag"],
	["le licenciement","die Kündigung"],
	["réduire","(auf + Akk.) herabstufen"],
	["le juge","der Richter"],
	["le conseil des prud’hommes","das Arbeitsgericht"],
	["la représentativité","die Repräsentativität"],
	["un référendum interne","eine betriebliche Abstimmung"],
	["le droit à la déconnection","das Recht zum Abschalten"],
	["favorable au salarié","arbeitnehmerfreundlich"],
	["arbitraire","willkürlich"],
	["la valeur de référence, valeur indicative","der Richtwert"],
	["etwas zulassen","permettre"],
	["le cas particulier","der Sonderfall"],
	["l’assouplissement","die Lockerung"],
	];
}
